# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(837, 538)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.sentiment_min = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sentiment_min.sizePolicy().hasHeightForWidth())
        self.sentiment_min.setSizePolicy(sizePolicy)
        self.sentiment_min.setObjectName("sentiment_min")
        self.gridLayout.addWidget(self.sentiment_min, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 3, 1, 1)
        self.price_min = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price_min.sizePolicy().hasHeightForWidth())
        self.price_min.setSizePolicy(sizePolicy)
        self.price_min.setObjectName("price_min")
        self.gridLayout.addWidget(self.price_min, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 3, 1, 1)
        self.sentiment_max = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sentiment_max.sizePolicy().hasHeightForWidth())
        self.sentiment_max.setSizePolicy(sizePolicy)
        self.sentiment_max.setObjectName("sentiment_max")
        self.gridLayout.addWidget(self.sentiment_max, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.price_max = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price_max.sizePolicy().hasHeightForWidth())
        self.price_max.setSizePolicy(sizePolicy)
        self.price_max.setObjectName("price_max")
        self.gridLayout.addWidget(self.price_max, 3, 0, 1, 1)
        self.filter_keyword = QtWidgets.QLineEdit(self.centralwidget)
        self.filter_keyword.setObjectName("filter_keyword")
        self.gridLayout.addWidget(self.filter_keyword, 1, 3, 1, 1)
        self.search_by_keyword = QtWidgets.QPushButton(self.centralwidget)
        self.search_by_keyword.setObjectName("search_by_keyword")
        self.gridLayout.addWidget(self.search_by_keyword, 1, 4, 1, 1)
        self.filter_product = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_product.sizePolicy().hasHeightForWidth())
        self.filter_product.setSizePolicy(sizePolicy)
        self.filter_product.setEditable(True)
        self.filter_product.setObjectName("filter_product")
        self.gridLayout.addWidget(self.filter_product, 1, 2, 1, 1)
        self.filter_brand = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_brand.sizePolicy().hasHeightForWidth())
        self.filter_brand.setSizePolicy(sizePolicy)
        self.filter_brand.setEditable(True)
        self.filter_brand.setObjectName("filter_brand")
        self.gridLayout.addWidget(self.filter_brand, 3, 2, 1, 1)
        self.show_people = QtWidgets.QPushButton(self.centralwidget)
        self.show_people.setObjectName("show_people")
        self.gridLayout.addWidget(self.show_people, 3, 3, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setObjectName("submit")
        self.horizontalLayout_2.addWidget(self.submit)
        spacerItem = QtWidgets.QSpacerItem(377, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setObjectName("quit")
        self.horizontalLayout_2.addWidget(self.quit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.message = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message.sizePolicy().hasHeightForWidth())
        self.message.setSizePolicy(sizePolicy)
        self.message.setMinimumSize(QtCore.QSize(0, 20))
        self.message.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.message.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.message.setText("")
        self.message.setObjectName("message")
        self.verticalLayout.addWidget(self.message)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.wordcloud = ImageView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordcloud.sizePolicy().hasHeightForWidth())
        self.wordcloud.setSizePolicy(sizePolicy)
        self.wordcloud.setObjectName("wordcloud")
        self.histogram = ImageView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogram.sizePolicy().hasHeightForWidth())
        self.histogram.setSizePolicy(sizePolicy)
        self.histogram.setObjectName("histogram")
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.save_results = QtWidgets.QPushButton(self.centralwidget)
        self.save_results.setEnabled(False)
        self.save_results.setObjectName("save_results")
        self.horizontalLayout.addWidget(self.save_results)
        self.show_results = QtWidgets.QPushButton(self.centralwidget)
        self.show_results.setObjectName("show_results")
        self.horizontalLayout.addWidget(self.show_results)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.price_min, self.price_max)
        MainWindow.setTabOrder(self.price_max, self.sentiment_min)
        MainWindow.setTabOrder(self.sentiment_min, self.filter_keyword)
        MainWindow.setTabOrder(self.filter_keyword, self.sentiment_max)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Sentiment Minimum"))
        self.label_3.setText(_translate("MainWindow", "Price Minimum"))
        self.sentiment_min.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Search By Keyword Review"))
        self.price_min.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Price Maximum"))
        self.label_10.setText(_translate("MainWindow", "Search By People"))
        self.sentiment_max.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Sentiment Maximum"))
        self.label_8.setText(_translate("MainWindow", "Search By Brand"))
        self.label_7.setText(_translate("MainWindow", "Search By Product"))
        self.price_max.setText(_translate("MainWindow", "0"))
        self.search_by_keyword.setText(_translate("MainWindow", "Search"))
        self.show_people.setText(_translate("MainWindow", "Show People"))
        self.submit.setText(_translate("MainWindow", "Submit"))
        self.quit.setText(_translate("MainWindow", "Quit"))
        self.save_results.setText(_translate("MainWindow", "Save current result"))
        self.show_results.setText(_translate("MainWindow", "Show saved results..."))

from image_view import ImageView
